- hosts: server
  tasks:
    - name: install python-docker centos
      yum:
        name: python-docker
        state: present
      when:
      - ansible_distribution == "CentOS"
    - name: install python3-docker ubuntu
      apt:
        name: python3-docker
        state: present
      when:
      - ansible_distribution == "Ubuntu"
    - name: create container
      docker_container:
        name: container_by_jenkins
        image: ibadoc/apache-ubuntu:100
        state: started
        published_ports:
          - 80:80
        recreate: yes
        interactive: yes
        detach: yes
  
